
Vagrant.configure("2") do |config|

 config.vm.define "serverEl" do |web|

        web.vm.box = "sbeliakou/centos"

        web.vm.hostname = "serverEl"

        web.vm.network :private_network, ip: "192.168.55.59"

        web.vm.provision :shell, :path => "server1_install.sh"

        web.vm.provider :virtualbox do |v|

                v.customize ["modifyvm", :id, "--memory", 2048]
                v.customize ["modifyvm", :id, "--name", "serverEl"]
                v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
  end

 config.vm.define "serverLog" do |web|

        web.vm.box = "sbeliakou/centos"

        web.vm.hostname = "serverLog"

        web.vm.network :private_network, ip: "192.168.55.60"

        web.vm.provision :shell, :path => "server2_install.sh"

        web.vm.provider :virtualbox do |v|

                v.customize ["modifyvm", :id, "--memory", 2048]
                v.customize ["modifyvm", :id, "--name", "serverLog"]
                v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
 end

end
