
Vagrant.configure("2") do |config|

 config.vm.define "zserver" do |web|

        web.vm.box = "sbeliakou/centos"

        web.vm.hostname = "zserver"

        web.vm.network :private_network, ip: "192.168.55.56"

        web.vm.provision :shell, :path => "server_install.sh"

        web.vm.provider :virtualbox do |v|

                v.customize ["modifyvm", :id, "--memory", 2048]
                v.customize ["modifyvm", :id, "--name", "zserver"]
                v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
  end

 config.vm.define "agentserver" do |web|

        web.vm.box = "sbeliakou/centos"

        web.vm.hostname = "agentserver"

        web.vm.network :private_network, ip: "192.168.55.55"

        web.vm.provision :shell, :path => "agent_install.sh"

        web.vm.provider :virtualbox do |v|

                v.customize ["modifyvm", :id, "--memory", 2048]
                v.customize ["modifyvm", :id, "--name", "agentserver"]
                v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
 end

end
